version: '2'

services:

        jenkins:

                image: jenkins

                container_name: jenkins

                ports:

                        - "8080:8080"

                        - "50000:50000"

                restart: always

                volumes:

                        - /var/jenkins_home:/var/jenkins_home
